baseURL = 'http://portfolio.anubhav-narayan'
languageCode = 'en-in'
title = 'Anubhav Mattoo'
theme = 'hugo-profile'

Paginate = 3
enableRobotsTXT = true

[outputs]
home = [ "HTML", "RSS", "JSON" ]
page = [ "HTML", "RSS" ]

[markup.goldmark.renderer]
unsafe = true

[[Menus.main]]
identifier = "blog"
name = "Blog"
title = "Blog posts"
url = "/blogs"
weight = 1

[[Menus.main]]
identifier = "gallery"
name = "Gallery"
title = "Blog posts"
url = "/gallery"
weight = 2

[params]
title = "Anubhav Mattoo"
description = "VLSI Engineer"
favicon = "/favicon-32x32.png"
useBootstrapCDN = false
animate = true

  [params.font]
  fontSize = "1rem"
  fontWeight = 400
  lineHeight = 1.5
  textAlign = "left"

  [params.navbar]
  align = "ms-auto"
  brandName = "Anubhav Mattoo"
  disableSearch = false

    [params.navbar.menus]
    disableAbout = false
    disableExperience = false
    disableEducation = false
    disableProjects = false
    disableAchievements = false
    disableContact = false

  [params.hero]
  enable = true
  intro = "Hi, my name is"
  title = "Anubhav."
  subtitle = "I build computers."
  content = "Yes, I shamelessly copied a huge template."
  image = "/images/hero.jpeg"

    [params.hero.button]
    enable = true
    name = "Resume"
    url = "#"
    download = true
    newPage = false

[[params.hero.socialLinks.fontAwesomeIcons]]
icon = "fab fa-github"
url = "https://github.com/anubhav-narayan"

[[params.hero.socialLinks.fontAwesomeIcons]]
icon = "fab fa-linkedin"
url = "https://linkedin.com/anubhav-mattoo"


  [params.about]
  enable = true
  title = "About Me"
  image = "/images/me.png"
  content = """
I am a VLSI Engineer with passion for digital & analogue electronics. I have a background in computer engineering, mathematics, and VLSI design. I am currently working as a VLSI Engineer at [C-DAC India.](https://cdac.in) in Pune, India. 
I am currently working on a project that will be used to create India's supercomputeing capability."""

    [params.about.skills]
    enable = true
    title = "Here are a few technologies I've been working with recently:"
    items = [ "Verilog", "SPICE", "VHDL", "Python3", "FORTRAN", "BASh" ]

  [params.experience]
  enable = true

    [[params.experience.items]]
    job = "Project Engineer"
    company = "C-DAC"
    companyUrl = "https://cdac.in"
    date = "Nov 2022 - present"
    content = "I am currently working as a FPGA Engineer at [C-DAC.](https://example.com) in Pune, India. I am currently working on a project that will be used for high performance computing at scale."

      [params.experience.items.featuredLink]
      enable = true
      name = "View the project"
      url = "https://cdac.in/index.aspx?id=hpc_cc_recounfigurable_computing"

    [[params.experience.items]]
    job = "Associate Support Engineer"
    company = "NICE"
    companyUrl = "https://nice.com"
    date = "Jun 2020 - May 2021"
    content = """
Joined the Satmetrix team for customer support.
- Developed API automation tooling for support and endpoint testing.
- Worked on various connectors and ETL integration tools.
"""

      [params.experience.items.featuredLink]
      enable = true
      url = "https://example.com"

      [params.experience.items.info]
      enable = true
      content = "I worked as a automation designer as we;;."

    
  [params.education]
  enable = true
  index = false

    [[params.education.items]]
    title = "Graduate Student in VLSI at C-DAC ACTS"
    date = "3/2022 - 10/2022"
    GPA = ""
    content = """
- Joined the C-DAC ACTS as a VLSI Student.
- Acquired skills in Digital CMOS Design workflow and FPGA workflow.
- Gained skills to integrate software-style workflow for Digital and Analogue CMOS design.
- Designed a encryption block using basic fiestel network and LFSRs.
    """

      [params.education.items.school]
      name = "C-DAC ACTS"
      url = "https://example.org"

    [[params.education.items]]
    title = "Bachelor of Engineering in Computer Engineering"
    date = "2017 - 2021"
    GPA = "8.92 out of 10.0"
    content = """
- Woked on Computer Engineering and design of computing hardware and software.
- Designed the Public Key Name System(PKNS) and DOPE Encryption Algorithm.
"""

      [params.education.items.school]
      name = "Savitribai Phule Pune University"
      url = "http://unipune.ac.in"

  [params.achievements]
  enable = false

    [[params.achievements.items]]
    title = "Google kickstart runner"
    content = "I solved all problems with optimal solution."
    url = "https://example.com"

    [[params.achievements.items]]
    title = "Facebook Hackathon Winner"
    content = "Developed a product using Artificial Intelligence."

    [[params.achievements.items]]
    title = "Hugo Profile"
    content = "Developed a theme and getting 1K+ downloads per month."
    url = "https://github.com/gurusabarish/hugo-profile"

    [[params.achievements.items]]
    title = "Microsoft Imagine Runner"
    content = "We are developed a product which can help others."

    [[params.achievements.items]]
    title = "Google Summer of Code"
    content = "Contributed to a open source project."
    url = "https://example.com"

  [params.projects]
  enable = true

    [[params.projects.items]]
    title = "Hugo Profile"
    content = "A highly customizable and mobile first Hugo template for personal portfolio and blog."
    image = "/images/projects/profile.png"
    badges = [ "Hugo", "Bootstrap", "Javascript" ]

      [params.projects.items.featured]
      name = "Demo"
      link = "https://hugo-profile.netlify.app"

      [[params.projects.items.links]]
      icon = "fa fa-envelope"
      url = "mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f"

      [[params.projects.items.links]]
      icon = "fab fa-github"
      url = "https://github.com/gurusabarish/hugo-profile"

      [[params.projects.items.links]]
      icon = "fab fa-twitter"
      url = "https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile"

    [[params.projects.items]]
    title = "Image Converter"
    content = "A web app to convert image to pdf, png to jpg, png to jpg and png to webp without database using django."
    image = "/images/projects/converter.jpg"
    badges = [ "Django", "Bootstrap" ]

      [params.projects.items.featured]
      name = "Demo"
      link = "https://django-converter.herokuapp.com"

      [[params.projects.items.links]]
      icon = "fab fa-github"
      url = "https://github.com/gurusabarish/converter"

    [[params.projects.items]]
    title = "Hugo Profile V2"
    content = "A clean and simple Hugo template for personal portfolio and blog."
    image = "/images/projects/profile2.jpg"
    badges = [ "Hugo", "Bootstrap", "Javascript" ]

      [params.projects.items.featured]
      name = "Demo V2"
      link = "https://hugo-profile-2.netlify.app"

      [[params.projects.items.links]]
      icon = "fab fa-github"
      url = "https://github.com/gurusabarish/HugoProfileV2"

  [params.contact]
  enable = true
  content = "My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!"
  email = "anubhavmattoo@outlook.com"
  btnName = "Mail me"

[params.footer.recentPosts]
path = "blogs"
count = 3
title = "Recent Posts"
enable = true
disableFeaturedImage = false

[params.footer.socialNetworks]
github = "https://github.com/anubhav-narayan"
linkedin = "https://linkedin.com/anubhav-mattoo"

  [params.listPages]
  disableFeaturedImage = false
